src/models/post_model.py
from src import db
from datetime import datetime


class Post(db.Model):
    __tablename__ = "posts"
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    content = db.Column(db.Text)
    # author = db.Column(db.String(255))
    created_at = db.Column(db.DateTime, default=datetime.utcnow())
    slug = db.Column(db.String(255))
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"))

src/models/user_model.py
from src import db, login_manager
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash
from datetime import datetime


@login_manager.user_loader
def load_user(user_id):
    return User.query.get_or_404(int(user_id))


class User(db.Model, UserMixin):
    __tablename__ = "users"
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(20), nullable=False, unique=True)
    name = db.Column(db.String(100), nullable=False)
    email = db.Column(db.String(80), nullable=False, unique=True)
    favorite_color = db.Column(db.String(120))
    about_author = db.Column(db.Text(), nullable=True)
    created_at = db.Column(db.DateTime, default=datetime.utcnow())
    password_hash = db.Column(db.String(128))
    is_admin = db.Column(db.Boolean, default=False)
    can_post = db.Column(db.Boolean, default=True)
    profile_pic = db.Column(db.String(128), nullable=True)
    posts = db.relationship("Post", backref="user")

    @property
    def password(self):
        raise AttributeError("Password is not a readable.")

    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f"User(id={self.id}, name={self.name}, email={self.email}, can_post={self.can_post})"

src/forms/webforms.py
from flask_ckeditor import CKEditorField
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, EmailField, PasswordField, RadioField, TextAreaField, FileField
from wtforms.validators import DataRequired, EqualTo


class UserForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    username = StringField("Username", validators=[DataRequired()])
    email = EmailField("Email", validators=[DataRequired()])
    favorite_color = StringField("Favorite Color")
    about_author = TextAreaField("About Author")
    password = PasswordField("Password", validators=[DataRequired(),
                                                     EqualTo("password_confirm", message="Passwords Must Match!")])
    password_confirm = PasswordField("Confirm Password", validators=[DataRequired()])
    profile_pic = FileField("Profile Picture")
    submit = SubmitField("Submit")


class EditUserForm(FlaskForm):
    name = StringField("Name", validators=[DataRequired()])
    username = StringField("Username", validators=[DataRequired()])
    email = EmailField("Email", validators=[DataRequired()])
    is_admin = RadioField("Is Admin", choices=[(True, "True"), (False, "False")],default=True, coerce=bool)
    can_post = RadioField("Can Post", choices=[(True, "True"), (False, "False")],default=True, coerce=bool)
    submit = SubmitField("Save")


# Create a Form Class
class NameForm(FlaskForm):
    name = StringField("What's Your Name", validators=[DataRequired()])
    submit = SubmitField("Submit")


# Password Form
class PasswordForm(FlaskForm):
    email = EmailField("What' Your Email.", validators=[DataRequired()])
    password = PasswordField("What's Your Password.", validators=[DataRequired()])
    submit = SubmitField("Submit")


# Login Form
class LoginForm(FlaskForm):
    username = StringField("Username", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Submit")


# Create Post Form
class PostForm(FlaskForm):
    title = StringField("Title", validators=[DataRequired()])
    content = CKEditorField("Content", validators=[DataRequired()])
    # author = StringField("Author", validators=[DataRequired()])
    slug = StringField("Slug", validators=[DataRequired()])
    submit = SubmitField("Submit")


# Search Form
class SearchForm(FlaskForm):
    searched = StringField("Searched", validators=[DataRequired()])
    submit = SubmitField("Submit")

src/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
from flask_bcrypt import Bcrypt
from flask_ckeditor import CKEditor
from src.configs import Config

db = SQLAlchemy()
bcrypt = Bcrypt()
ckeditor = CKEditor()

login_manager = LoginManager()
login_manager.login_view = "users.login"
login_manager.login_message_category = "info"


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    login_manager.init_app(app)
    bcrypt.init_app(app)
    ckeditor.init_app(app)
    migrate = Migrate(app,db)

    from src.blueprints.users import users
    from src.blueprints.posts import posts
    from src.blueprints.errors import errors

    app.register_blueprint(users)
    app.register_blueprint(posts)
    app.register_blueprint(errors)

    return app

src/blueprints/errors.py
from flask import Blueprint, render_template

errors = Blueprint("errors", __name__)


@errors.app_errorhandler(404)
def page_not_found(e):
    return render_template("404.html"), 404


@errors.app_errorhandler(500)
def page_internal_server_error(e):
    return render_template("500.html"), 500


@errors.app_errorhandler(403)
def forbidden_error(e):
    return render_template("403.html"), 403

src/blueprints/posts.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

from src.forms.webforms import PostForm
from src.services.post_service import PostService

posts = Blueprint("posts", __name__)


@posts.route("/add-post", methods=["GET", "POST"])
@login_required
def create_post():
    form = PostForm()
    if current_user.can_post:
        return PostService.create_post(form)
    return render_template("403.html")


@posts.route("/posts")
def show_posts():
    return PostService.render_all_posts()


@posts.route("/posts/<int:post_id>")
def get_post(post_id):
    return PostService.view_post_by_id(post_id)


@posts.route("/posts/edit/<int:post_id>", methods=["GET", "POST"])
@login_required
def edit_post(post_id):
    return PostService.edit_post(post_id)


@posts.route("/posts/delete/<int:post_id>")
@login_required
def delete_post(post_id):
    return PostService.delete_post(post_id)


@posts.route("/search", methods=["POST"])
def search():
    return PostService.search_post()

src/blueprints/users.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

from src.forms.webforms import UserForm, LoginForm, EditUserForm, SearchForm
from src.services.users_service import UserService

users = Blueprint("users", __name__)

UPLOAD_FOLDER = "static/images"


@users.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    return UserService.user_login(form)


@users.route("/register/", methods=["GET", "POST"])
def add_user():
    form = UserForm()
    return UserService.registration(form)


@users.route("/users/<int:user_id>", methods=["GET", "POST"])
@login_required
def update_user(user_id):
    form = UserForm()
    return UserService.update_user(form, user_id)


@users.route("/delete/<int:user_id>")
@login_required
def delete_user(user_id):
    return UserService.delete_user(user_id)


@users.route("/admin")
@login_required
def admin():
    if current_user.is_admin:
        search_form = SearchForm()
        all_users = UserService.get_all_users()
        return render_template("admin.html", users=all_users, search_form=search_form)
    return render_template("403.html")


@users.route("/admin/edit/<int:user_id>", methods=["GET", "POST"])
@login_required
def edit_user(user_id):
    if current_user.is_admin:
        return UserService.edit_by_admin(user_id)
    return render_template("403.html")


@users.route("/admin/search", methods=["GET", "POST"])
@login_required
def search_user():
    if current_user.is_admin:
        return UserService.search_user()
    return render_template("403.html")


@users.route("/dashboard", methods=["GET", "POST"])
@login_required
def dashboard():
    form = UserForm()
    user_id = current_user.id
    return UserService.user_dashboard(form, user_id)


# Logout Page
@users.route("/logout", methods=["GET", "POST"])
@login_required
def logout():
    return UserService.user_logout()


@users.route("/")
def index():
    return render_template("index.html")

src/templates/add_user.html
{% extends 'base.html' %}

{% block content %}

{% with messages =  get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<br>
<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="POST">
        {{ form.hidden_tag() }}

        {{ form.name.label(class='from-label') }}
        {{ form.name(class='form-control') }}
        <br>
        {{ form.username.label(class='from-label') }}
        {{ form.username(class='form-control') }}
        <br>
        {{ form.email.label(class='from-label') }}
        {{ form.email(class='form-control') }}
        <br>
        {{ form.favorite_color.label(class='from-label') }}
        {{ form.favorite_color(class='form-control') }}
        <br>
        {{ form.password.label(class='from-label') }}
        {{ form.password(class='form-control') }}
        <br>
        {{ form.password_confirm.label(class='from-label') }}
        {{ form.password_confirm(class='form-control') }}
        <br>
        {{ form.submit(class='btn btn-secondary') }}
    </form>
</div>

{% endblock %}

src/templates/admin.html
{% extends 'base.html' %}

{% block content %}
<div>
    <form action="{{ url_for('users.search_user') }}" method="POST">
        <div class="form-group my-2" >
             {{ form.hidden_tag() }}
            <label for="user_search" class="form-lable">Search user: </label>
            {{ search_form.searched(placeholder='Enter username') }}
            {{ search_form.submit(class='btn btn-outline-secondary btn-sm', value='Search') }}
            <a href="{{url_for('users.admin') }}" class="btn btn-outline-secondary btn-sm">Reset</a>
        </div>
    </form>
</div>
<table class="table shadow mt-3">
    <thead>
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Name</th>
        <th scope="col">Username</th>
        <th scope="col">Email</th>
        <th scope="col">Is Admin</th>
        <th scope="col">Can Post</th>
        <th scope="col" class="text-center">Settings</th>

    </tr>
    </thead>
    <tbody>
    {% if user %}
        <tr>
            <th scope="row">{{ user.id }}</th>
            <td>{{ user.name }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.is_admin }}</td>
            <td>{{ user.can_post }}</td>
            <td class="">
                <div class="row">
                    <div class="col">
                         <a type="button" class="btn btn-primary" href="{{ url_for('users.edit_user', user_id=user.id) }}">Edit
                </a>
                    </div>
                    <div class="col">
                        <a type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{ user.id }}">Delete</a>
                    </div>
                </div>
                {% include 'delete_modal.html' %}
            </td>
        </tr>
    {% else %}
        {% for user in users %}
        <tr>
            <th scope="row">{{ user.id }}</th>
            <td>{{ user.name }}</td>
            <td>{{ user.username }}</td>
            <td>{{ user.email }}</td>
            <td>{{ user.is_admin }}</td>
            <td>{{ user.can_post }}</td>
            <td class="">
                <div class="row">
                    <div class="col">
                         <a type="button" class="btn btn-primary" href="{{ url_for('users.edit_user', user_id=user.id) }}">Edit
                </a>
                    </div>
                    <div class="col">
                        <a type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{ user.id }}">Delete</a>
                    </div>
                </div>
                {% include 'delete_modal.html' %}
            </td>
        </tr>
        {% endfor %}
    {% endif %}
    </tbody>
</table>
{% endblock %}

src/templates/create_post.html
{% extends 'base.html' %}

{% block content %}

{% with messages =  get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<h1>Add Blog Post:</h1>
<br>
<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.title.label(class='from-label') }}
        {{ form.title(class='form-control') }}
        <br>
        {{ form.slug.label(class='from-label') }}
        {{ form.slug(class='form-control') }}
        <br>
        {{ form.content.label(class='from-label') }}
        {{ form.content(class='form-control', rows='10') }}
        <br>
        {{ form.submit(class='btn btn-secondary') }}
    </form>
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='content') }}
</div>
{% endblock %}

src/templates/dashboard.html
{% extends 'base.html' %}

{% block content %}

{% with messages =  get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}


    <h2>User Profile</h2>
    <br>
    <div class="card">
        <div class="card-header">
            {{ current_user.name }}
        </div>
        <div class="card-body">
            <div class="container">
                <div class="row">
                    <div class="col-8">
                        <p class="card-text">
                            <strong>Name: </strong>{{ current_user.name }}<br>
                            <strong>Username: </strong>{{ current_user.username }}<br>
                            <strong>Email: </strong>{{ current_user.email }}<br>
                            <strong>Favorite Color: </strong>{{ current_user.favorite_color }}<br>
                            <strong>About Author: </strong>{{ current_user.about_author }}<br>
                            <strong>Date Joined: </strong>{{ current_user.created_at }}<br>
                        </p>
                        <a href="{{ url_for('users.update_user',user_id=current_user.id) }}"
                           class="btn btn-secondary btn-sm">Update Profile</a>
                         <a type="button" class="btn btn-danger btn-sm" data-bs-toggle="modal" data-bs-target="#delete{{ current_user.id }}">Delete</a>
                        <!-- Modal -->
                        <div class="modal fade" id="delete{{ current_user.id }}" tabindex="-1"
                             aria-labelledby="deleteModalLabel" aria-hidden="true">
                            <div class="modal-dialog">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <h4 class="modal-title" id="deleteModalLabel">Delete User</h4>
                                        <button type="button" class="btn-close" data-bs-dismiss="modal"
                                                aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <h5>Are you sure you want to delete user : '{{ current_user.username }}'?</h5>
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close
                                        </button>
                                        <form action="{{ url_for('users.delete_user', user_id=current_user.id) }}">
                                            <a href="{{ url_for('users.delete_user', user_id=current_user.id) }}"
                                               class="btn btn-danger">Delete</a>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-4">
                        {% if current_user.profile_pic %}
                        <img src="{{ url_for('static', filename='images/'+ current_user.profile_pic) }}" width="180" align="right"
                             alt="User">
                        {% else %}
                        <img src="{{ url_for('static', filename='images/default-user.jpg') }}" width="180" align="right"
                             alt="User">
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
<br>
    <div class="card">
        <div class="card-header">
           Update Profile
        </div>
        <div class="card-body">
            <form action="{{ url_for('users.dashboard') }}" method="POST" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                {{ form.name.label(class='from-label') }}
                {{ form.name(class='form-control', value=user_to_update.name) }}
                <br>
                {{ form.username.label(class='from-label') }}
                {{ form.username(class='form-control', value=user_to_update.username) }}
                <br>
                {{ form.email.label(class='from-label') }}
                {{ form.email(class='form-control', value=user_to_update.email) }}
                <br>
                {{ form.favorite_color.label(class='from-label') }}
                {{ form.favorite_color(class='form-control', value=user_to_update.favorite_color) }}
                <br>
                {{ form.about_author.label(class='from-label') }}
                <textarea name="about_author" class="form-control">{{ user_to_update.about_author }}</textarea>
                <br>
                {{ form.profile_pic.label(class='from-label') }}
                {{ form.profile_pic(class='form-control') }}
                <br>
                {{ form.submit(class='btn btn-secondary btn-sm') }}
            </form>
        </div>
    </div>


    {% endblock %}

src/templates/delete_modal.html
<!-- Modal -->
<div class="modal fade" id="delete{{ user.id }}" tabindex="-1" aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title" id="deleteModalLabel">Delete User</h4>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
      <h5>Are you sure you want to delete user : '{{ user.username }}'?</h5>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <form action="{{ url_for('users.delete_user', user_id=user.id) }}">
                 <a href="{{ url_for('users.delete_user', user_id=user.id) }}" class="btn btn-danger">Delete</a>
            </form>
      </div>
    </div>
  </div>
</div>

src/templates/edit_post.html
{% extends 'base.html' %}

{% block content %}

{% with messages =  get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

{% if current_user.id==post.user.id %}
<br>
<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="POST">
        {{ form.hidden_tag() }}

        {{ form.title.label(class='from-label') }}
        {{ form.title(class='form-control', value=post.title) }}
        <br>
        {{ form.slug.label(class='from-label') }}
        {{ form.slug(class='form-control', value=post.slug) }}
        <br>
        {{ form.content.label(class='from-label') }}
        {{ form.content(class='form-control', rows='10') }}
        <br>
        {{ form.submit(class='btn btn-secondary') }}
    </form>
    {{ ckeditor.load() }}
    {{ ckeditor.config(name='content') }}
</div>

{% endif %}
<a href="{{ url_for('posts.show_posts') }}" class="btn btn-outline-secondary btn-sm">Back to Blog</a>

{% endblock %}

src/templates/index.html
{% extends 'base.html' %}

{% block content %}



{% endblock %}

src/templates/login.html
{% extends 'base.html' %}

{% block content %}

{% with messages =  get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}


<h1>Login</h1>
<br><br><br>

<div class="shadow p-3 mb-5 bg-body rounded">
    <form method="POST">
        {{ form.hidden_tag() }}

        {{ form.username.label(class='from-label') }}
        {{ form.username(class='form-control') }}
        <br>
        {{ form.password.label(class='from-label') }}
        {{ form.password(class='form-control') }}
        <br>
        {{ form.submit(class='btn btn-secondary') }}
    </form>
</div>

{% endblock %}

src/templates/name.html
{% extends 'base.html' %}

{% block content %}
{% with messages =  get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
    <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% endif %}
{% endwith %}
{% if name %}
    <h1>Hello {{ name }}!!</h1>
    <br>
    <img src="{{ url_for('static', filename='images/baby_yoda.jpg') }}" width="600", height="300" alt="">
    <br><br>
    <p id="demo">This is stuff...</p>
    <script src="{{ url_for('static', filename='js/sample.js') }}"></script>
{% else %}
    <h1>What's Your Name?!</h1>
    <br>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.name.label(class='from-label') }}
        {{ form.name(class='form-control') }}
        <br>
        {{ form.submit(class='btn btn-secondary') }}
    </form>

{% endif %}

{% endblock %}

src/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="{{ url_for('users.index') }}">Dark City</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if current_user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.dashboard') }}">User Profile</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('posts.create_post') }}">Add Post</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('posts.show_posts') }}">Posts</a>
            </li>
            {% if current_user.is_admin %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.admin') }}">Admin</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.logout') }}">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.login') }}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{{ url_for('users.add_user') }}">Register</a>
            </li>
            {% endif %}
        </ul>
      <form class="d-flex" method="POST" action="{{ url_for('posts.search') }}">
        {{ form.hidden_tag() }}
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched">
        <button class="btn btn-outline-secondary" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

src/templates/post.html
{% extends 'base.html' %}

{% block content %}

{% with messages =  get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<br>
<div class="shadow p-3 mb-5 bg-body rounded">
    <h2>{{ post.title }}</h2>
    <small>By: {{ post.user.name }}<br>
        {{ post.created_at }}</small><br><br>
    {{ post.content|safe }}<br>
    <div class="card mb-3">
        <div class="row no-gutters">
            <div class="col-md-2">
                {% if post.user.profile_pic %}
                <img src="{{ url_for('static', filename='images/'+ post.user.profile_pic) }}" width="150" align="left" alt="User Picture">
                {% else %}
                <img src="{{ url_for('static', filename='images/default-user.jpg') }}" width="150" align="left" alt="User Picture">
                {% endif %}
            </div>
            <div class="col-md-10">
                <div class="card-body">
                    <h5 class="card-title">{{ post.user.name }}</h5>
                    <p class="card-text">
                        {% if post.user.about_author %}
                        {{ post.user.about_author }}
                        {% else %}
                        Author has no about profile...
                        {% endif %}
                    </p>
                </div>
            </div>
        </div>
    </div>
</div>
{% if current_user.id == post.user.id %}
<a href="{{ url_for('posts.edit_post', post_id=post.id) }}" class="btn btn-outline-secondary btn-sm">Edit Post</a>
<a href="{{ url_for('posts.delete_post', post_id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete Post</a>
{% endif %}
<a href="{{ url_for('posts.show_posts') }}" class="btn btn-outline-secondary btn-sm">Back to Blog</a>


{% endblock %}

src/templates/posts.html
{% extends 'base.html' %}

{% block content %}

{% with messages =  get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
<div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
    <strong>{{ message }}</strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
{% endfor %}
{% endif %}
{% endwith %}

<br>
{% for post in posts %}
<div class="shadow p-3 mb-5 bg-body rounded">
    <h2><a href="{{ url_for('posts.get_post', post_id=post.id) }}">{{ post.title }}</a></h2>
    <small>By: {{ post.user.name }}<br>
    {{ post.created_at }}</small><br><br>
    {{ post.content|safe }}<br><br>
    <a href="{{ url_for('posts.get_post', post_id=post.id) }}" class="btn btn-outline-secondary btn-sm">View Post</a>
    {% if current_user.id == post.user.id or current_user.is_admin %}
    <a href="{{ url_for('posts.edit_post', post_id=post.id) }}" class="btn btn-outline-secondary btn-sm">Edit Post</a>
    <a href="{{ url_for('posts.delete_post', post_id=post.id) }}" class="btn btn-outline-danger btn-sm">Delete Post</a>
    {% endif %}
    <br>
</div>
{% endfor %}

{% endblock %}

src/templates/test_pw.html
{% extends 'base.html' %}

{% block content %}
{% with messages =  get_flashed_messages(with_categories=true) %}
{% if messages %}
{% for category, message in messages %}
    <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
        <strong>{{ message }}</strong>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
{% endfor %}
{% endif %}
{% endwith %}
{% if email %}
    <h1>Email: {{ email }}</h1>
    <h1>Password: {{ password }}</h1>
    <br>
    <h2>I found this info:</h2>
    Name: {{ user_check.name }}<br>
    Email: {{ user_check.email }}<br>
    PW: {{ user_check.password_hash }}<br>
    <br>
    Passed: {{ passed }}

{% else %}
    <h1>What's Your Email and Password?!</h1>
    <br>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.email.label(class='from-label') }}
        {{ form.email(class='form-control') }}
        <br>
        {{ form.password.label(class='from-label') }}
        {{ form.password(class='form-control') }}
        <br>
        {{ form.submit(class='btn btn-secondary') }}
    </form>

{% endif %}

{% endblock %}

src/templates/user.html
{% extends 'base.html' %}

{% block content %}

<h1>Hello {{ user_name|capitalize }}</h1>

{% endblock %}